### ISSUE TITLE
Suspected bug: cannot pickle and unpickle 

### ISSUE THREAD

**Issue by gilirosenberg12** [jtiosue/qubovert#39]
Pickling and then unpickling a `PUSO` currently fails even for a trivial `PUSO`, see below. This severely limits the ability to use `qubovert` since one cannot save and load problems...

Minimal example:
```python
import pickle
pickle.loads(pickle.dumps(PUSO({('a',):1})))
```

which gives an `AttributeError` that is tracked back to the `degree` property:
```python
    380 k = self.__class__.squash_key(key)
    381 if value:
--> 382     self._degree = max(self._degree, len(k))
    383     for i in filter(lambda x: x not in self._variables, k):
    384         self._variables.add(i)

AttributeError: 'PUSO' object has no attribute '_degree'
```

**Comment by jtiosue** [comment]
Hi @gilirosenberg12. Yes I have come across this before. Perhaps one day I will get rid of all the underscores, though unfortunately I use underscores in front of attributes everywhere. Instead of pickle, might I suggest the functions [qubovert.utils.get_info](https://qubovert.readthedocs.io/en/latest/utils/methods.html#qubovert.utils.get_info) and [qubovert.utils.create_from_info](https://qubovert.readthedocs.io/en/latest/utils/methods.html#qubovert.utils.create_from_info). Personally, I have had issues with pickle in the past where I have stored data in pickled form and then tried to come back to it years later only to have the issue that I am using a different python version, pickle version, etc. and I could not retrieve the data. Therefore, I personally refer this approach, where you the information is written in json form.

As a minimal example with the trivial PUSO as you showed, you would do as follows. 

```
info = qv.utils.get_info(qv.PUSO({('a',): 1}))
# write info to a file
# come back some time later, read info from the file
puso = qv.utils.create_from_info(info)
```

**Comment by jtiosue** [comment]
Please let me know if you have anything else related to this issue, otherwise I will close it.

**Comment by souravsanyal06** [comment]
I am facing this issue. What would be a suitable way to save and load qubovert object types ?

**Comment by jtiosue** [comment]
Hi @souravsanyal06, I would recommend following Tip 17 in the [qubovert_tutorial.ipynb](https://github.com/jtiosue/qubovert/blob/master/notebook_examples/qubovert_tutorial.ipynb) notebook (scroll down close to the end and look for "Tip 17"). In summary, the `qubovert.utils.get_info` function takes in a qubovert object and returns a dict (which you can then write to a file, etc). The `qubovert.utils.create_from_info` takes a dict and returns a qubovert object. For reference, the documentation for the functions is [here](https://qubovert.readthedocs.io/en/latest/utils/methods.html?highlight=get_info#qubovert.utils.get_info) and [here](https://qubovert.readthedocs.io/en/latest/utils/methods.html?highlight=get_info#qubovert.utils.create_from_info).

**Comment by souravsanyal06** [comment]
Actually, I just tried this out and it works. Thanks a lot for the prompt response!

**Comment by souravsanyal06** [comment]
On a side note, is it possible to convert the qubovert object into an equivalent networkx graph ?

**Comment by jtiosue** [comment]
There is currently no function in qubovert that does this, but it should be very straightforward by just iteration through the keys of a qubovert object.

**Comment by souravsanyal06** [comment]
Yes thanks. I did it using the Q.Q to get the matrices and stepping through
them. Thanks.
