### ISSUE TITLE
During the calculation, a variable is missing

### ISSUE THREAD

**Issue by ffiamz** [jtiosue/qubovert#50]
```python
>>> import qubovert as qv
>>> x = qv.PUBO({('a[0][0][0]', 'q_w_L[1][0][0]'): 4.0, ('a[0][0][0]', 'q_w_L[0][0][0]'): 2.0, ('a[0][0][0]',): -2.0, ('q_w_L[1][0][0]',): -2.0, ('q_w_L[0][0][0]',): -1.0, (): 1.0})
>>> x * x
{('q_w_L[0][0][0]', 'q_w_L[1][0][0]'): 4.0, ('q_w_L[0][0][0]',): -1.0, (): 1.0}
```
why is 'a[0][0][0]' missing?

**Comment by jtiosue** [comment]
This is not a bug, this is indeed the correct answer. Every coefficient involving `'a[0][0][0]'` in `x*x` is zero. Let me simplify the notation to `Q = {('x0', 'x1'): 4.0, ('x0', 'x2'): 2.0, ('x0',): -2.0, ('x1',): -2.0, ('x2',): -1.0, (): 1.0}`. This is describing 
$$Q = 4x_0 x_1 + 2 x_0 x_2 - 2x_0 - 2 x_1 - x_2 + 1 .$$
So we get
$$Q^2 = 16 x_1^2 x_0^2+4 x_2^2 x_0^2-16 x_1 x_0^2+16 x_1 x_2 x_0^2-8 x_2 x_0^2+4 x_0^2-16 x_1^2 x_0-4 x_2^2 x_0+16 x_1 x_0-16 x_1 x_2 x_0+8 x_2 x_0-4 x_0+4 x_1^2+x_2^2-4 x_1+4 x_1 x_2-2 x_2+1 .$$
But recall that $x_0, x_1,x_2$ are binary variables so that $x_0^2 = x_0$, $x_1^2 = x_1$, and $x_2^2 = x_2$. So we get
$$Q^2 = 16 x_1 x_0+4 x_2 x_0-16 x_1 x_0+16 x_1 x_2 x_0-8 x_2 x_0+4 x_0-16 x_1 x_0-4 x_2 x_0+16 x_1 x_0-16 x_1 x_2 x_0+8 x_2 x_0-4 x_0+4 x_1+x_2-4 x_1+4 x_1 x_2-2 x_2+1 ,$$
which you can easily check is equal to
$$Q = 4 x_1 x_2-x_2+1,$$
so that `Q * Q` should indeed be `{('x1', 'x2'): 4, ('x2',): -1, (): 1}`. There is no `x0` variable anymore because all terms involving `x0` are zero.
